version: "4.0.0.{build}"

platform: Any CPU
configuration: Release
skip_tags: true

environment:
  BUILDWINRT: true
  USINGMONO: false
  SNKSECRET:
    secure: C8FL0UTKVN8YcMW1wdssabbkSWMIrpJTqgUNeI2NfQw=

init:
  - appveyor DownloadFile https://download.microsoft.com/download/A/3/8/A38489F3-9777-41DD-83F8-2CBDFAB2520C/packages/DotNetCore.1.0.0-SDK.Preview2-x64.exe
  - DotNetCore.1.0.0-SDK.Preview2-x64.exe /quiet
  - echo %APPVEYOR_BUILD_VERSION%
  - choco install -y rabbitmq

install:
  - IF DEFINED SNKSECRET (nuget install secure-file -ExcludeVersion)
  - IF DEFINED SNKSECRET (secure-file\tools\secure-file -decrypt %APPVEYOR_BUILD_FOLDER%\rabbit.snk.enc -secret %SNKSECRET%) ELSE (ECHO This Is A Pull Request Build)
  - IF NOT DEFINED SNKSECRET (copy "rabbit.snk.prbuilds" "rabbit.snk") ELSE (ECHO Using The Release Key File)
  - ps: |
      $regPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ"
      if (Test-Path "HKLM:\SOFTWARE\Wow6432Node\") { $regPath = "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\RabbitMQ" }
      $path = Split-Path -Parent (Get-ItemProperty $regPath "UninstallString").UninstallString
      $version = (Get-ItemProperty $regPath "DisplayVersion").DisplayVersion
      [Environment]::SetEnvironmentVariable("RABBITMQ_HOME", "$path\rabbitmq_server-$version", "Machine")
      $env:RABBITMQ_HOME = "$path\rabbitmq_server-$version"
      [Environment]::SetEnvironmentVariable("RABBITMQ_RABBITMQCTL_PATH", "$path\rabbitmq_server-$version\sbin\rabbitmqctl.bat", "Machine")
      $env:RABBITMQ_RABBITMQCTL_PATH = "$path\rabbitmq_server-$version\sbin\rabbitmqctl.bat"

before_build:

build_script: 
    - cmd: .\build.bat
    - cmd: .\run-test.bat
    - ps: |
        $suffix = Get-Date -format "yyyyMMddhhss"
        Write-Host $suffix
        dotnet pack "projects\client\RabbitMQ.Client" -c Release --version-suffix=ci-$suffix

test: off

after_build:

artifacts:
  - path: '*.nupkg'
  - path: 'projects\client\RabbitMQ.Client\bin\Release\*.nupkg'
  - path: '*.log'
    name: Logs

deploy: off

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

branches:
    only:
    - master
    - stable
